spring:
  config:
    import: "optional:classpath:application-env.properties"
  application:
    name: ChonsreBack

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect

kakao:
  redirect_uri: ${KAKAO_REDIRECT_URI}
  api:
    key: ${KAKAO_API_KEY}

openai:
  api-key: ${OPENAI_API_KEY}

tourapi:
  base-url: "https://apis.data.go.kr/B551011/KorService2"
  key-enc: ${TOUR_API_KEY_ENC}
  key-dec: ${TOUR_API_KEY_DEC}

dataset:
  jeonnam:
    path: datasets/jeonnam_rural.xlsx
  region-fixed: "전라남도"               # '시도'는 없으니 전남 고정값 추가
  columns:
    category: "구분"       # 농촌/어촌/기타 등
    county: "시군"         # 예: 여수시, 순천시
    place: "장소명"        # 마을 이름
    address: "주소"        # 전체 주소
    desc: "체험"           # 체험 프로그램

  # 👇 여기가 columns와 같은 'dataset' 하위 레벨이어야 합니다 (columns 안 X)
  jeonnam-json:
    path: classpath:datasets/JeonNam.xlsx   # 실제 리소스 위치 (대소문자 주의)
    sheet-index: 0                          # 기본 시트








logging:
  level:
    root: INFO
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http: DEBUG